/**
 * State → county (or county-equivalent) mapping.
 *
 * Seeded with a working subset for the states most relevant to operations.
 * Add additional states as needed — structure is identical for all entries.
 * Louisiana uses "parishes"; Alaska uses "boroughs / census areas"; all others are counties.
 */
export const STATE_COUNTIES: Record<string, string[]> = {
  NJ: [
    "Atlantic",
    "Bergen",
    "Burlington",
    "Camden",
    "Cape May",
    "Cumberland",
    "Essex",
    "Gloucester",
    "Hudson",
    "Hunterdon",
    "Mercer",
    "Middlesex",
    "Monmouth",
    "Morris",
    "Ocean",
    "Passaic",
    "Salem",
    "Somerset",
    "Sussex",
    "Union",
    "Warren",
  ],
  NY: [
    "Albany",
    "Allegany",
    "Bronx",
    "Broome",
    "Cattaraugus",
    "Cayuga",
    "Chautauqua",
    "Chemung",
    "Chenango",
    "Clinton",
    "Columbia",
    "Cortland",
    "Delaware",
    "Dutchess",
    "Erie",
    "Essex",
    "Franklin",
    "Fulton",
    "Genesee",
    "Greene",
    "Hamilton",
    "Herkimer",
    "Jefferson",
    "Kings",
    "Lewis",
    "Livingston",
    "Madison",
    "Monroe",
    "Montgomery",
    "Nassau",
    "New York",
    "Niagara",
    "Oneida",
    "Onondaga",
    "Ontario",
    "Orange",
    "Orleans",
    "Oswego",
    "Otsego",
    "Putnam",
    "Queens",
    "Rensselaer",
    "Richmond",
    "Rockland",
    "St. Lawrence",
    "Saratoga",
    "Schenectady",
    "Schoharie",
    "Schuyler",
    "Seneca",
    "Steuben",
    "Suffolk",
    "Sullivan",
    "Tioga",
    "Tompkins",
    "Ulster",
    "Warren",
    "Washington",
    "Wayne",
    "Westchester",
    "Wyoming",
    "Yates",
  ],
  FL: [
    "Alachua",
    "Baker",
    "Bay",
    "Bradford",
    "Brevard",
    "Broward",
    "Calhoun",
    "Charlotte",
    "Citrus",
    "Clay",
    "Collier",
    "Columbia",
    "DeSoto",
    "Dixie",
    "Duval",
    "Escambia",
    "Flagler",
    "Franklin",
    "Gadsden",
    "Gilchrist",
    "Glades",
    "Gulf",
    "Hamilton",
    "Hardee",
    "Hendry",
    "Hernando",
    "Highlands",
    "Hillsborough",
    "Holmes",
    "Indian River",
    "Jackson",
    "Jefferson",
    "Lafayette",
    "Lake",
    "Lee",
    "Leon",
    "Levy",
    "Liberty",
    "Madison",
    "Manatee",
    "Marion",
    "Martin",
    "Miami-Dade",
    "Monroe",
    "Nassau",
    "Okaloosa",
    "Okeechobee",
    "Orange",
    "Osceola",
    "Palm Beach",
    "Pasco",
    "Pinellas",
    "Polk",
    "Putnam",
    "St. Johns",
    "St. Lucie",
    "Santa Rosa",
    "Sarasota",
    "Seminole",
    "Sumter",
    "Suwannee",
    "Taylor",
    "Union",
    "Volusia",
    "Wakulla",
    "Walton",
    "Washington",
  ],
};
