"use server";

import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export type SubmitProjectState = {
  error: string | null;
};

export async function submitProject(
  _prevState: SubmitProjectState,
  formData: FormData
): Promise<SubmitProjectState> {
  const supabase = await createClient();

  // ── 1. Verify authenticated user ──────────────────────────────────────────
  const { data: userData, error: userError } = await supabase.auth.getUser();
  if (userError || !userData.user) {
    return { error: "You must be signed in to submit a project." };
  }

  const userId = userData.user.id;

  // ── 2. Look up the user's company_id ──────────────────────────────────────
  const { data: membership, error: membershipError } = await supabase
    .from("company_memberships")
    .select("company_id")
    .eq("user_id", userId)
    .single();

  if (membershipError || !membership) {
    return { error: "Your account is not associated with a company. Contact your administrator." };
  }

  const companyId = membership.company_id;

  // ── 3. Parse and validate required fields ─────────────────────────────────
  const jobName = (formData.get("job_name") as string)?.trim();
  const requestedApprovalDate = formData.get("requested_approval_date") as string | null;
  const jobAddress = (formData.get("job_address") as string)?.trim();
  const authorityTypeRaw = (formData.get("authority_type") as string)?.toLowerCase();
  const county = (formData.get("county") as string)?.trim();
  const city = (formData.get("city") as string)?.trim();
  const typeOfPlanRaw = (formData.get("type_of_plan") as string)?.toLowerCase();
  const jobTypeRaw = (formData.get("job_type") as string)?.toLowerCase();

  if (!jobName) return { error: "Job Name is required." };
  if (!requestedApprovalDate) return { error: "Requested Approval Date is required." };
  if (!jobAddress) return { error: "Job Address is required." };
  if (!authorityTypeRaw) return { error: "Authority Type is required." };
  if (!county) return { error: "County is required." };
  if (!city) return { error: "City is required." };
  if (!typeOfPlanRaw) return { error: "Type of Plan is required." };
  if (!jobTypeRaw) return { error: "Job Type is required." };

  // Map display values to enum values
  const authorityTypeMap: Record<string, string> = {
    county: "county",
    njdot: "njdot",
    municipal: "municipal",
    other: "other",
  };
  const planTypeMap: Record<string, string> = {
    aerial: "aerial",
    underground: "underground",
    mixed: "mixed",
    other: "other",
  };
  const jobTypeMap: Record<string, string> = {
    tcp: "tcp",
    sld: "sld",
    "full package": "full_package",
    full_package: "full_package",
    revision: "revision",
    other: "other",
  };

  const authorityType = authorityTypeMap[authorityTypeRaw];
  const typeOfPlan = planTypeMap[typeOfPlanRaw];
  const jobType = jobTypeMap[jobTypeRaw];

  if (!authorityType) return { error: "Invalid authority type." };
  if (!typeOfPlan) return { error: "Invalid plan type." };
  if (!jobType) return { error: "Invalid job type." };

  // Optional fields
  const rhinoPM = (formData.get("rhino_pm") as string)?.trim() || null;
  const comcastManager = (formData.get("comcast_manager") as string)?.trim() || null;
  const jobNumberClient = (formData.get("job_number_client") as string)?.trim() || null;
  const submittedToFiberpro = (formData.get("submitted_to_fiberpro") as string) || null;
  const township = (formData.get("township") as string)?.trim() || null;
  const notes = (formData.get("notes") as string)?.trim() || null;

  // ── 4. Insert project record ───────────────────────────────────────────────
  // job_number is auto-generated by DB trigger; pass empty string to trigger it
  const { data: project, error: insertError } = await supabase
    .from("projects")
    .insert({
      job_number: "",          // trigger overwrites this
      company_id: companyId,
      submitted_by: userId,
      status: "intake_review",
      billing_status: "not_ready",
      job_name: jobName,
      job_number_client: jobNumberClient,
      rhino_pm: rhinoPM,
      comcast_manager: comcastManager,
      submitted_to_fiberpro: submittedToFiberpro || null,
      requested_approval_date: requestedApprovalDate,
      job_address: jobAddress,
      authority_type: authorityType,
      county,
      city,
      township,
      type_of_plan: typeOfPlan,
      job_type: jobType,
      notes,
    })
    .select("id")
    .single();

  if (insertError || !project) {
    console.error("Project insert error:", insertError);
    return { error: "Failed to create project. Please try again." };
  }

  // ── 5. Create initial activity record ─────────────────────────────────────
  await supabase.from("project_activity").insert({
    project_id: project.id,
    actor_id: userId,
    actor_label: userData.user.email ?? "Company User",
    action: "Project submitted",
    metadata: { source: "company_submit" },
  });

  // ── 6. Redirect to new project detail page ────────────────────────────────
  // NOTE: redirect() throws and must be called outside try/catch
  redirect(`/company/projects/${project.id}`);
}
